### ISSUE TITLE
Spark line not drawn 

### ISSUE THREAD

**Issue by RohitWani** [PredixDev/px-vis-spark#2]
Hello Team,

We are using the px-vis-spark to build configurable widgets and some time ago ran into a issue where the spark line is not rendered/drawn. There are some typical cases when this happens, as detailed below.

[We also have a requirement from our stakeholder to show gradient along with the sparkline. Can you please provide the support.]

## Steps to reproduce the problem:
         
case 1: last y in data is zero

<px-vis-spark type="line" height="50" width="300"  data='[ {"x":1397102460000,"y":56},
                                              {"x":1397139660000,"y":4},
                                              {"x":1397177400000,"y":43},
                                              {"x":1397228040000,"y":33},
                                              {"x":1397248260000,"y":47},
                                              {"x":1397291280000,"y":41},
                                              {"x":1397318100000,"y":26},
                                              {"x":1397342100000,"y":11},
                                              {"x":1397390820000,"y":27},
                                              {"x":1397408100000,"y":38},
                                              {"x":1397458800000,"y":36},
                                              {"x":1397522940000,"y":0}]'  prevent-resize="true"></px-vis-spark>

case 2: last y in  data is string or NaN
<px-vis-spark type="line" height="50" width="300" data='[ {"x":1397102460000,"y":56},
                                              {"x":1397139660000,"y":4},
                                              {"x":1397177400000,"y":43},
                                              {"x":1397228040000,"y":33},
                                              {"x":1397248260000,"y":47},
                                              {"x":1397291280000,"y":41},
                                              {"x":1397318100000,"y":26},
                                              {"x":1397342100000,"y":11},
                                              {"x":1397390820000,"y":27},
                                              {"x":1397408100000,"y":38},
                                              {"x":1397458800000,"y":36},
                                              {"x":1397522940000,"y":NaN}]' prevent-resize="true"></px-vis-spark>

case 3: Value of y somewhere in the array is not present
<px-vis-spark type="line" height="50" width="300" data='[ {"x":1397102460000,"y":56},
                                              {"x":1397139660000,"y":4},
                                              {"x":1397177400000,"y":43},
                                              {"x":1397228040000,"y":33},
                                              {"x":1397248260000,"y":47},
                                              {"x":1397291280000,"y":41},
                                              {"x":1397318100000,"y":26},
                                              {"x":1397342100000,"y":},
                                              {"x":1397390820000,"y":27},
                                              {"x":1397408100000,"y":38},
                                              {"x":1397458800000,"y":36},
                                              {"x":1397522940000,"y":NaN}]' prevent-resize="true"></px-vis-spark>

case 4: Value of y somewhere in the array is other than number and string
<px-vis-spark type="line" height="50" width="300" data='[ {"x":1397102460000,"y":56},
                                              {"x":1397139660000,"y":4},
                                              {"x":1397177400000,"y":43},
                                              {"x":1397228040000,"y":33},
                                              {"x":1397248260000,"y":47},
                                              {"x":1397291280000,"y":41},
                                              {"x":1397318100000,"y":26},
                                              {"x":1397342100000,"y": abc},
                                              {"x":1397390820000,"y":27},
                                              {"x":1397408100000,"y":38},
                                              {"x":1397458800000,"y":36},
                                              {"x":1397522940000,"y":NaN}]' prevent-resize="true"></px-vis-spark>

## Steps to reproduce:
Value of y somewhere in the array is string/NaN, except at the ends

<px-vis-spark type="line" height="50" width="300" data='[ {"x":1397102460000,"y":56},
                                              {"x":1397139660000,"y":4},
                                              {"x":1397177400000,"y":43},
                                              {"x":1397228040000,"y":33},
                                              {"x":1397248260000,"y":47},
                                              {"x":1397291280000,"y":41},
                                              {"x":1397318100000,"y":26},
                                              {"x":1397342100000,"y":NaN},
                                              {"x":1397390820000,"y":27},
                                              {"x":1397408100000,"y":38},
                                              {"x":1397458800000,"y":36},
                                              {"x":1397522940000,"y":NaN}]' prevent-resize="true"></px-vis-spark>

## Screenshot for this:
![break1](https://cloud.githubusercontent.com/assets/18310416/22346329/b5542a6c-e429-11e6-9fc4-4d28028ce6d9.PNG)

## Environment 
(_component version number = "0.1.10",  Browser= chrome  55.0.2883.87, operating system= Windows7)

. 
We really need the fix to be able to go into production. Looking forward for the support and fix.

Thanks,
Rohit

**Comment by nonmetalhail** [comment]
Hi,

Case 1: `0` will be fixed in the next release when vis 1.x is released. Probably some time in February. This will fix the problem where `0` shows a gap. 

Case 2: `NaN` provides a gap as there is no data at that point. That is expected behavior and will continue in the next release.

Case 3: `strings` are not supported and will provide an undefined behavior (IE we can will not guarantee what will draw). The values for the sparkline data must be of `Number` type.

Case 4: `null` and `NaN` will provide a gap in the line. `undefined` and the line will connect between the last two points. Other types, Boolean, etc, are not supported and will yield an undefined behavior. Again, the only supported type for the values of this chart are `Numbers`.

The gradient has not been prioritized by PM and there is no schedule for developing it at this time. We may get to it when we have some free time, but cannot guarantee any delivery date.
