### ISSUE TITLE
<script> tag outside of <dom-module>

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis-spark#3]
Hi,

It may be an oversight, but I see several script tags outside their respective dom-module.
AFAIK, code for the element registration must be enclosed within the <dom-module> tag.
Could that be changed or would you accept a PR to change that?

**Comment by mdwragg** [comment]
Hi,

Can you please submit issues following the template laid out when you create a new issue. What problem are you observing? On which browsers? Screenshots of the issue?

Thanks.

**Comment by davidsteinberger** [comment]
It's funny, b/c again I did not get the template populated. Nevertheless here's the proper description:

## Expected behavior and actual behavior:

IMO _px-vis-spark.html_ shall use a local dom structure as outlined by the [Polymer project](https://www.polymer-project.org/1.0/docs/devguide/local-dom). In a nutshell it's like:

    <dom-module id="x-foo">

      <template>I am x-foo!</template>

      <script>
        Polymer({
          is: 'x-foo'
        });
      </script>

    </dom-module>

In contrast to that _px-vis-spark_ has a script-tag outside of the dom-module.

## Steps to reproduce the problem:

Use the component in a browser that supports shadow dom and lazy load polymer.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

At least v0.2.3 and v1.0.0; I haven't checked others

**Comment by mdwragg** [comment]
My apologies, you are quite right. For some reason our templates seem to be missing from a few of our repos. We will rectify that ASAP.

Again, sorry and thank you for your issues.

**Comment by nonmetalhail** [comment]
Hi, It actually doesnt matter where the script tag is located. Although all the examples have the script inside the dom-module, the polymer docs state, "The <script> tag can be inside or outside of the <dom-module> element." 

I'm not really sure if there are any differences between the locations, but all our components are set up this way and it seems not to be a problem, so we are loath to change it.
