### ISSUE TITLE
Html imports wrong

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis-spark#6]
## Expected behavior and actual behavior:

The component uses 2 html imports that are IMO wrong:

Actual:

    <link rel="import" href="../px-vis-behavior-common.html">
    <link rel="import" href="../bower_components/px-colors-design/colors.html" />

Expected:

    <link rel="import" href="../px-vis/px-vis-behavior-common.html">
    <link rel="import" href="../px-colors-design/colors.html" />

Moreover _px-colors-design_ should be added as a bower dependency.

Shall I send a PR?

## Steps to reproduce the problem:

use any v1.0.x version

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

N/A

**Comment by nonmetalhail** [comment]
That looks wrong to me too. A PR would be lovely :) 

Thanks

**Comment by randyaskin** [comment]
I took care of it, since I'm probably the fool who did it in the first place. :)  Fixed in v1.0.2.

**Comment by benoitjchevalier** [comment]
Should colors design actually be a dependency? Haven't looked at the code but assuming this is only used to generate css

**Comment by randyaskin** [comment]
Yes, I'm using the behavior not the sass. Not sure if there's a better way to do it, I think I modeled it after the other simple charts.

**Comment by davidsteinberger** [comment]
Thanks! I just saw that you set the dep for _px-colors-design_ to _^v0.3.9_. Do you think that could be further raised to ^v1.0.0?

**Comment by randyaskin** [comment]
Colors v1 is still in pre-release state. We'll bump the dependency to v1 when we also bump and pre-release px-vis-spark as part of the redesign.
