### ISSUE TITLE
Spark-line breaks its continuity for Analog type of input over a period of time

### ISSUE THREAD

**Issue by inaw-tihor** [PredixDev/px-vis-spark#8]
# Submit an Issue

Hi,

We are facing issue with the spark line. We have an Analog type of series which is used as an input for the px-vis-spark component. I was able to reproduce the problem on the predix-ui site (https://www.predix-ui.com/#/elements/vis/px-vis-spark) with a sample data, as mentioned below. 

Please help with the resolution.

## Steps to reproduce the problem:
Visit the Px-vis demo site: https://www.predix-ui.com/#/elements/vis/px-vis-spark

Enter the data as:
Data: [{"x":1397102460000,"y":-250},{"x":1397139660000,"y":-250},{"x":1397177400000,"y":-250},{"x":1397228040000,"y":375},{"x":1397248260000,"y":375},{"x":1397291280000,"y":375},{"x":1397318100000,"y":-250},{"x":1397342100000,"y":-250},{"x":1397390820000,"y":-250},{"x":1397408100000,"y":375},{"x":1397458800000,"y":375},{"x":1397522940000,"y":375}]

## Environment ( _component version number: latest,
                            Browser (Google chrome Version 60.0.3112.113), 
                            operating system(Mac Os X), Apple )

## Screenshots :
<img width="733" alt="screen shot 2017-09-09 at 3 28 28 am" src="https://user-images.githubusercontent.com/26837694/30232688-016b2c5c-950f-11e7-8141-24cba2def91e.png">

**Comment by nonmetalhail** [comment]
@randyaskin is spark line supposed to support negative values? Or does the design specify only positive values?

**Comment by randyaskin** [comment]
I wasn't really given a spec at the time this was created, but I don't see any reason why it _shouldn't_ support negative values.

**Comment by inaw-tihor** [comment]
Do we have a fix for the issue.

**Comment by nonmetalhail** [comment]
When we have a fix, we'll close the issue

**Comment by nonmetalhail** [comment]
fixed in v3

**Comment by inaw-tihor** [comment]
Great. 

But noticed that there is a change in color (from blue to black).  
Is the color also driven by a polymer property or is it default.

![image](https://user-images.githubusercontent.com/26837694/30381972-8eb1b900-98bb-11e7-8a56-6b438e39fe36.png)

**Comment by randyaskin** [comment]
If you aren't using [px-theme](https://www.predix-ui.com/#/develop/migrate/theme) in your application, you can style this particular element with the [CSS variable](https://www.polymer-project.org/1.0/docs/devguide/styling#custom-style) named `--px-vis-series-color-0`
