### ISSUE TITLE
Error thrown when resize occurs before data is bound

### ISSUE THREAD

**Issue by midgetspy** [PredixDev/px-vis-spark#9]
https://github.com/PredixDev/px-vis-spark/blob/1c3a5440be87a5bf3da23bfc0c609ce9c7d0b9c0/px-vis-spark.html#L215

The above line expects `#wrapper` to exist but that element is inside a `dom-if` which is only stamped if `data` is set:

https://github.com/PredixDev/px-vis-spark/blob/1c3a5440be87a5bf3da23bfc0c609ce9c7d0b9c0/px-vis-spark.html#L36

So if a resize event is fired before data is set then `this.$$('#wrapper')` is null so an exception is thrown and the component remains the default size.

**Comment by randyaskin** [comment]
Not sure if that dom-if is even necessary (I think I added it for px-kpi, which is probably where the dom-if really belongs), but I added a null check in v3.0.3.

**Comment by midgetspy** [comment]
Null check does not fix the problem, in that case the resize event isn't processed and the component is forevermore the wrong (default) size.
